public class StateCreator {
    public static void main(String[] ars) {
        District districtHotimsk = new District("Хотимский");
        districtHotimsk.cityAdd(new City("Хотимск"));
        districtHotimsk.cityAdd(new City("Тростино"));
        districtHotimsk.cityAdd(new City("Забелышин"));
        District districtShklov = new District("Шкловский");
        districtShklov.cityAdd(new City("Благовка"));
        districtShklov.cityAdd(new City("Брус"));
        districtShklov.cityAdd(new City("Борки-1"));
        District districtBihov = new District("Быховский");
        districtBihov.cityAdd(new City("Адаменко"));
        districtBihov.cityAdd(new City("Барсуки"));
        districtBihov.cityAdd(new City("Бовки"));
        Region regionMogilev = new Region("Могилевская", "Могилев");
        regionMogilev.districtAdd(districtBihov);
        regionMogilev.districtAdd(districtHotimsk);
        regionMogilev.districtAdd(districtShklov);
        District districtBaranovichy = new District("Барановичский");
        districtBaranovichy.cityAdd(new City("Русино"));
        districtBaranovichy.cityAdd(new City("Новые Луки"));
        districtBaranovichy.cityAdd(new City("Ковши"));
        District districtPinsk = new District("Пинский");
        districtPinsk.cityAdd(new City("Гольцы"));
        districtPinsk.cityAdd(new City("Тупчицы"));
        districtPinsk.cityAdd(new City("Лопатино"));
        District districtKobrin = new District("Кобринский");
        districtKobrin.cityAdd(new City("Адаменко"));
        districtKobrin.cityAdd(new City("Барсуки"));
        districtKobrin.cityAdd(new City("Бовки"));
        Region regionBrest = new Region("Брестская", "Брест");
        regionBrest.districtAdd(districtBaranovichy);
        regionBrest.districtAdd(districtPinsk);
        regionBrest.districtAdd(districtKobrin);
        District districtBragin = new District("Брагинский");
        districtBragin.cityAdd(new City("Александровка"));
        Region regionGomel = new Region("Гомельская", "Гомель");
        regionGomel.districtAdd(districtBragin);
        District districtSlonim = new District("Слонимский");
        districtSlonim.cityAdd(new City("Антоновка"));
        Region regionGrodno = new Region("Гродненская", "Гродно");
        regionGrodno.districtAdd(districtSlonim);
        District districtLepel = new District("Лепельский");
        districtLepel.cityAdd(new City("Александровка"));
        Region regionVitebsk = new Region("Витебская", "Витебск");
        regionVitebsk.districtAdd(districtLepel);
        District districtMolodechno = new District("Молодечненский");
        districtMolodechno.cityAdd(new City("Молодечно"));
        Region regionMinsk = new Region("Минская", "Минск");
        regionMinsk.districtAdd(districtMolodechno);
        State stateBelarus = new State("Беларусь", "Минск", "207,6 тыс. кв.км");
        stateBelarus.regionAdd(regionBrest);
        stateBelarus.regionAdd(regionMinsk);
        stateBelarus.regionAdd(regionMogilev);
        stateBelarus.regionAdd(regionGomel);
        stateBelarus.regionAdd(regionGrodno);
        stateBelarus.regionAdd(regionVitebsk);
        System.out.println(stateBelarus);
    }
}
